### ISSUE TITLE
Make the main Container stylish!

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#10]
# Making the Container!

* Making the main container(where currently welcome is written) much styled with features like a border having boundaries on all 4 sides so adjust accordingly .
* Add Color grading 
* Change its shape to more like a somewhat in between a rectangle and a circle i guess ! 
* Also remove the "welcome" text and its corresponding widget completely...

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by Harshsharma44** [comment]
assigned to Shubhankit-Pandey

**Comment by Shubhankit-Pandey** [comment]
Actually haven't started yet because of other issues but will surely complete it before the deadline.

**Comment by Harshsharma44** [comment]
oh okay contributor!
