### ISSUE TITLE
Getting hands with lists!

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#11]
# Lists
Yeah lists are basic part of any app, we use it everywhere so in order to add lists or iterables(which we can convert further into list)
We need to add a lot of widgets, which would not be great, would it be? 

## Let's Say
* I want to add the same main container on my screen 20 times!
* I want to have some space in between every container
* Be careful! Bugs ahead, if faced solve them mortals!

### The Saviour
Widget X is the saviour and has many forms, use the widget X! 

Good luck!

**Comment by anjalii14** [comment]
claim

**Comment by Harshsharma44** [comment]
Assigned to anjalii14
