### ISSUE TITLE
Splash like a flash!

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#16]
# Splash Screen

Well good apps generally have splash screens with simple or no animations according to the purpose and theme of the app.

## The following tasks are to be done:
* Design a splash screen with suitable designs and animations!
* All work related to splash screen should be done in a Stateful widget(also a class) named "Splash".
* After opening the app 3 seconds of splash screen should be shown then redirect the user to the main screen by replacing the splash screen with the main one!
* Do not add any other directory or dart file other than assets or animation assets.
* _If animation and design is very good and classy, extra points will be rewarded!_

**Comment by anjalii14** [comment]
CLAIM

**Comment by BINGABABA** [comment]
Claim

**Comment by anjalii14** [comment]
CLAIM

**Comment by Harshsharma44** [comment]
assigned to BINGABABA

**Comment by RibhavBansal** [comment]
Claim

**Comment by Harshsharma44** [comment]
Issue is open to be assigned now

**Comment by RibhavBansal** [comment]
claim

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by Harshsharma44** [comment]
Assigned to RibhavBansal

**Comment by BINGABABA** [comment]
claim

**Comment by Harshsharma44** [comment]
BINGABABA you have unassigned this issue before

**Comment by BINGABABA** [comment]
can you reassign me

**Comment by anjalii14** [comment]
claim

**Comment by Harshsharma44** [comment]
No I can't reassign a previously unassigned issue!

**Comment by Harshsharma44** [comment]
Issue done
