### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#21]
# SideDrawer
We all know how important part of an app a drawer, your job is to design and implement one!

## Some important information:
* Attach an image (take one of the image from the asset folder) at the begining column of the drawer.
* Then Add three panel-type naming Tips, Profile and Settings Screen.
* Design the UI like if the current screen selected looks like the Tips Screen(the screen we were working on so far is Tips screen).
* Add colors and stylish color grading to the drawer as well!

### Something like this should be the interface 

![image](https://user-images.githubusercontent.com/97427100/208872907-394a6fc7-0ef7-4d13-be22-631385b66a2f.png)

Goodluck if you get some bugs out there!

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by anshgeez31** [comment]
claim

**Comment by Harshsharma44** [comment]
Assigned to Shubhankit-Pandey

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by anjalii14** [comment]
claim
