### ISSUE TITLE
Navigation through Screens

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#22]
# Navigation

* Make a new screen named Test.dart 
* On clicking any one of the containers, user should be redirected on the Test.dart page and at the center of the page the number should be shown, for example if i had clicked on a "4" written container, i should be shown "4" on the Test.dart screen
* Also implement a back button without the use of the Appbar, instead make use of the SafeArea widget

If you have any doubt you can ping me at discord!

**Comment by anshgeez31** [comment]
claim

**Comment by Harshsharma44** [comment]
assigned to anshgeez31

**Comment by anjalii14** [comment]
claim

**Comment by Harshsharma44** [comment]
any updates on the issue?

**Comment by anshgeez31** [comment]
@Harshsharma44 learning and progressing

**Comment by anjalii14** [comment]
claim

**Comment by anjalii14** [comment]
claim

**Comment by Harshsharma44** [comment]
assigned to anjalii14
