### ISSUE TITLE
Make a transition animation!

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#23]
# Animation 
* Make a suitable transition animation while going from one page to another.
* No need for you to add any page but you can attach a demo of the transition animation you have created in some demo project and then making a function of it, function name should be "Transit" and it should make a good animation while navigating from one page to another! 

In case if you have any doubts ping me once at discord!

**Comment by anshgeez31** [comment]
claim

**Comment by akshatsgh** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by Harshsharma44** [comment]
assigned to akshatsgh

**Comment by anjalii14** [comment]
claim

**Comment by Harshsharma44** [comment]
Any progress on this issue?

**Comment by anjalii14** [comment]
claim

**Comment by akshatsgh** [comment]
I would like to pass this issue to someone else

**Comment by anjalii14** [comment]
claim

**Comment by Harshsharma44** [comment]
assigned to anjalii14
