### ISSUE TITLE
Make a Login Screen!

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#27]
# Login Screen
Let's discuss the main points of this task:

* Make a login screen named LogIn.dart and no need to connect it to any page just make a login screen which takes 3 inputs as
* Use one of the designs Logo as part of good UI:
 1. User Name 
 2. User Phone Number
 3. User Password 
* Add a Submit button which will allow to submit and use the concept of Form, use TextFormField instead of TextField...
* You have to attach a demo of the Screen you have just created.
### Also good emphasis on the validation of the form and how it is implemented should be in mind as well.

Goodluck!

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by akshayw1** [comment]
Claim
