### ISSUE TITLE
Fetch fetch fetch!

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#32]
# Data Fetching 

Your job will be a long one for this task, you have to find a suitable API for our app which shows fitness tips etc. then from that API 
show the list of items on our ListContainers.

## Must Read before proceeding:
* Ping me once on discord you find a suitable API so I will approve whether to use it or not.
* Fetch the data using https package methods.
* From the API we need two things firstly the image of the content and then the description.
*  ### Most Importantly after clicking on the container, we want the full description of the content along with the same image.
* Which means on mainscreen page only the image and short description will be required.

This is a long task and requires patience to do! 
If you have any doubts you can ping me on the discord channel!

### GoodLuck!

**Comment by anjalii14** [comment]
claim

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by bhumika-kalaru** [comment]
claim
