### ISSUE TITLE
Implement

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#33]
# Implementation

* Implement the transition function while switching from Login Screen and going to mainscreen.dart 
* No need to alter any files or anything just implement the function 
* The code for the transition function is already there just implement it!

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by anjalii14** [comment]
claim

**Comment by bhumika-kalaru** [comment]
claim

**Comment by anjalii14** [comment]
claim
