### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#34]
## Create a profile page
 Create a profile page and name the Screen as Profile.dart, suitable with:

* A space for User to see their pfp (by default insert the image of any random person from the web)
* A space for User to upload a short description of themselves 
* A space for User contact details like phone number, email etc.
* Design should be done well!

### Note : Do not connnect the Profile Screen with any screen and do not alter any other files other then the assets directory and the pubsec.yaml file!

**Comment by bhumika-kalaru** [comment]
claim

**Comment by abhinavs1920** [comment]
Claim

**Comment by Harshsharma44** [comment]
any updates on the issue bhumika-kalaru?

**Comment by anjalii14** [comment]
claim

**Comment by bhumika-kalaru** [comment]
@Harshsharma44  yeah I'm working on it
