### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#39]
# Settings 

* Make a suitable settings page with functionalities like 
* Turn on music, turn off music
*  Logout, change
* Name  
* Change Password
Note: Do not connect this page with any Screen and please attach a demo of the Screen that you have created!

**Comment by piyushjha0409** [comment]
I would like to work on this issue, if you permit, I will start it right away!

**Comment by Harshsharma44** [comment]
Okay Assigned to you piyush!

**Comment by piyushjha0409** [comment]
Yeah I am on it dont worry.

**Comment by Harshsharma44** [comment]
This is the last day to complete your issue contributor!
