### ISSUE TITLE
Profile Page 

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#42]
# Profile Page 

#### Insert a container then Show the following
* User Name
* User Phone
* User Password 

Also Decorate it well and add some cool background animations like color grading changing etc.
for Name and Password and Phone number insert the default value as Name as FitezoUser , Password as 12345 and phone as 123456789

Have some doubts reach out to me on discord!

**Comment by anjalii14** [comment]
claim

**Comment by Harshsharma44** [comment]
you have been assigned an issue already on this repo!

**Comment by anjalii14** [comment]
I've completed the assigned issue.

**Comment by Harshsharma44** [comment]
ok this issue assigned to you then
