### ISSUE TITLE
UI (Descriptions of tips Page)

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#43]
# Tips Description

### On the tips Description Page add a good :
* Background instead of black
* Font color and font style to the text!
* Add a back button to go back to Tips page!

This is Screen where you will make changes do not temper with other screens!
![image](https://user-images.githubusercontent.com/97427100/210979083-0861f15c-c835-4484-ac9d-bf9c7df91a3b.png)

**Comment by bhumika-kalaru** [comment]
Claim

**Comment by Harshsharma44** [comment]
any updates ?
