### ISSUE TITLE
Small changes

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#46]
# Changes
On the page FitDiet.dart make some changes for the gridview to look something like this:

![image](https://user-images.githubusercontent.com/97427100/211256218-d6280045-6174-4563-9643-e0cabd26c659.png)

### Notice that an appbar is also been added there!

**Comment by sushantk1274** [comment]
claim

**Comment by SichangiFelix** [comment]
I would like to work on this

**Comment by Harshsharma44** [comment]
assigned to you SichangiFelix

**Comment by SichangiFelix** [comment]
Just created a PR for this issue
