### ISSUE TITLE
Icon for the Fitezo!

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#5]
# Design!

Well basically you have to design a suitable app logo for the Fitezo app keeping in mind the fitness theme of the app.

## This issue is **_Open for All_**.
 There is no need to claim this issue. You can directly submit a PR!

### Some points you should know before you start:

* Import the suitable design you have created on figma or whatever you use to design .
* Add a directory naming "assets" from the root directory as the base directory for example :

![image](https://user-images.githubusercontent.com/97427100/208249738-fafd2014-dffb-4982-a258-875656c270f9.png)

* In the asset directory import the image with the name "images-yourname" with a png or jpg extension is required!

**Comment by anjalii14** [comment]
claim

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by Harshsharma44** [comment]
No need to claim, this is an open for all repo !
 Read the Description first..

**Comment by Harshsharma44** [comment]
Issue closed
