### ISSUE TITLE
Remove the Appbar!

### ISSUE THREAD

**Issue by Harshsharma44** [opencodeiiita/Fitezo#6]
# AppBar

## What is it?
Well Basically it is the little box at the top of the screen where the words "Fitezo" is written as the title. 

Your task is to remove the Appbar.

### Why?
Well it looks kinda boring and not that much connected to the main UI of the application and more beautiful applications these days use without appbar designs in flutter.

## Important Points 

* You have to ensure that overflow or you know get mixed with the status bar.
* For this to function well there is already in built widget provided by the Flutter Framework.
* Find the Widget X and use it to make these easier for you as well as for the UI of the app.
* In replacement of the AppBar use a Container and its child as Row Widget to accomplish the same features that the appbar provides. 
* Also use a column widget to allow us to add a container after we replace our AppBar to continue our journey!

**Comment by anjalii14** [comment]
claim

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by BINGABABA** [comment]
claim

**Comment by Harshsharma44** [comment]
> claim

Issue assigned

**Comment by RibhavBansal** [comment]
claim
